-- What is the total revenue generated by male vs female customers ?
select gender, sum(purchase_amount) as revenue from customer
group by gender

select * from customer
limit 10
-- Which customers used a discount but still spent more than the average  purchase amount ?

select customer_id,purchase_amount from customer
where discount_applied = 'Yes' and 
purchase_amount > (
	select avg(purchase_amount) 
	from customer)
	
--Which are the top 5 products with the highest average review rating ?

select item_purchased , round(avg(review_rating::numeric),2) as "Average Product Rating" 
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5


-- Compare the average Purchase amount between Standard and review rating?
select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

-- Do subscribed customers spend more ? Compare average spend and total 
-- revenue between subscriber and non-subscribers.
select subscription_status,
Count(customer_id) as total_customers,
Round(avg(purchase_amount),2) as avg_spend,
Round(avg(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue , avg_spend desc ;

-- Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
Round(100*sum(case when discount_applied = 'Yes' then 1 Else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Segment customers into  New, Returning, and Loyal Basesd on their total
--number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
Case 
	When previous_purchases = 1 then 'New'
	When previous_purchases Between 2 and 10 then 'Retuning'
	Else 'Loyal'
	End As customer_segment
from customer

)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

-- What are the top 3 most purchased products within eaxh category?
with item_counts as (
select category,
item_purchased,
Count(customer_id) as total_orders,
Row_Number() over(partition by category order by count(customer_id) Desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;

-- Are customers Who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status

-- What is the revenue contribution of each age group?
select age_group,
Sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

